# Site settings
title: aladingzl Blog
SEOTitle: aladingzl 的博客 | aladingzl Blog
header-img: img/home-bg.jpg
email: zhaolongding@foxmail.com
description: "FE | aladingzl | 这里是我的个人博客"
keyword: "丁兆龙, 丁兆龙的博客, aladingzl, Dzl Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端"
url: "https://oopss.cn/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     aladingzl
zhihu_username:     aladingzl
github_username:    aladingzl
# twitter_username:   aladingzl
#facebook_username:  
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: https-aladingzl-github-io

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 073d3c2b59fd7919608bc9946182532b

# Google Analytics
ga_track_id: 'UA-217911135-1'            # Format: UA-xxxxxx-xx
ga_domain: oopss.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "前端爱好者， 不断学习中 <br> 立志成为一名优秀的 coder "
sidebar-avatar: https://github.com/aladingzl.png # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "(乱序) Mvbbb",
        href: "https://mvbbb.cn/"
    },{
        title: "Jev0n",
        href: "https://jev0n.com/"
    }
]
